// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: seckill.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Product_AddOrderItems_FullMethodName     = "/proto.product/AddOrderItems"
	Product_UpdateOrderItems_FullMethodName  = "/proto.product/UpdateOrderItems"
	Product_DelOrderItems_FullMethodName     = "/proto.product/DelOrderItems"
	Product_GetOrderItemsById_FullMethodName = "/proto.product/GetOrderItemsById"
	Product_SearchOrderItems_FullMethodName  = "/proto.product/SearchOrderItems"
	Product_AddOrders_FullMethodName         = "/proto.product/AddOrders"
	Product_UpdateOrders_FullMethodName      = "/proto.product/UpdateOrders"
	Product_DelOrders_FullMethodName         = "/proto.product/DelOrders"
	Product_GetOrdersById_FullMethodName     = "/proto.product/GetOrdersById"
	Product_SearchOrders_FullMethodName      = "/proto.product/SearchOrders"
	Product_AddProducts_FullMethodName       = "/proto.product/AddProducts"
	Product_UpdateProducts_FullMethodName    = "/proto.product/UpdateProducts"
	Product_DelProducts_FullMethodName       = "/proto.product/DelProducts"
	Product_GetProductsById_FullMethodName   = "/proto.product/GetProductsById"
	Product_SearchProducts_FullMethodName    = "/proto.product/SearchProducts"
	Product_UpdatesStatus_FullMethodName     = "/proto.product/UpdatesStatus"
)

// ProductClient is the client API for Product service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductClient interface {
	// -----------------------orderItems-----------------------
	AddOrderItems(ctx context.Context, in *AddOrderItemsReq, opts ...grpc.CallOption) (*AddOrderItemsResp, error)
	UpdateOrderItems(ctx context.Context, in *UpdateOrderItemsReq, opts ...grpc.CallOption) (*UpdateOrderItemsResp, error)
	DelOrderItems(ctx context.Context, in *DelOrderItemsReq, opts ...grpc.CallOption) (*DelOrderItemsResp, error)
	GetOrderItemsById(ctx context.Context, in *GetOrderItemsByIdReq, opts ...grpc.CallOption) (*GetOrderItemsByIdResp, error)
	SearchOrderItems(ctx context.Context, in *SearchOrderItemsReq, opts ...grpc.CallOption) (*SearchOrderItemsResp, error)
	// -----------------------orders-----------------------
	AddOrders(ctx context.Context, in *AddOrdersReq, opts ...grpc.CallOption) (*AddOrdersResp, error)
	UpdateOrders(ctx context.Context, in *UpdateOrdersReq, opts ...grpc.CallOption) (*UpdateOrdersResp, error)
	DelOrders(ctx context.Context, in *DelOrdersReq, opts ...grpc.CallOption) (*DelOrdersResp, error)
	GetOrdersById(ctx context.Context, in *GetOrdersByIdReq, opts ...grpc.CallOption) (*GetOrdersByIdResp, error)
	SearchOrders(ctx context.Context, in *SearchOrdersReq, opts ...grpc.CallOption) (*SearchOrdersResp, error)
	// -----------------------products-----------------------
	AddProducts(ctx context.Context, in *AddProductsReq, opts ...grpc.CallOption) (*AddProductsResp, error)
	UpdateProducts(ctx context.Context, in *UpdateProductsReq, opts ...grpc.CallOption) (*UpdateProductsResp, error)
	DelProducts(ctx context.Context, in *DelProductsReq, opts ...grpc.CallOption) (*DelProductsResp, error)
	GetProductsById(ctx context.Context, in *GetProductsByIdReq, opts ...grpc.CallOption) (*GetProductsByIdResp, error)
	SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error)
	UpdatesStatus(ctx context.Context, in *UpdatesStatusReq, opts ...grpc.CallOption) (*UpdatesStatusResp, error)
}

type productClient struct {
	cc grpc.ClientConnInterface
}

func NewProductClient(cc grpc.ClientConnInterface) ProductClient {
	return &productClient{cc}
}

func (c *productClient) AddOrderItems(ctx context.Context, in *AddOrderItemsReq, opts ...grpc.CallOption) (*AddOrderItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrderItemsResp)
	err := c.cc.Invoke(ctx, Product_AddOrderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) UpdateOrderItems(ctx context.Context, in *UpdateOrderItemsReq, opts ...grpc.CallOption) (*UpdateOrderItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderItemsResp)
	err := c.cc.Invoke(ctx, Product_UpdateOrderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DelOrderItems(ctx context.Context, in *DelOrderItemsReq, opts ...grpc.CallOption) (*DelOrderItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelOrderItemsResp)
	err := c.cc.Invoke(ctx, Product_DelOrderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) GetOrderItemsById(ctx context.Context, in *GetOrderItemsByIdReq, opts ...grpc.CallOption) (*GetOrderItemsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderItemsByIdResp)
	err := c.cc.Invoke(ctx, Product_GetOrderItemsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) SearchOrderItems(ctx context.Context, in *SearchOrderItemsReq, opts ...grpc.CallOption) (*SearchOrderItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchOrderItemsResp)
	err := c.cc.Invoke(ctx, Product_SearchOrderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) AddOrders(ctx context.Context, in *AddOrdersReq, opts ...grpc.CallOption) (*AddOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrdersResp)
	err := c.cc.Invoke(ctx, Product_AddOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) UpdateOrders(ctx context.Context, in *UpdateOrdersReq, opts ...grpc.CallOption) (*UpdateOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrdersResp)
	err := c.cc.Invoke(ctx, Product_UpdateOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DelOrders(ctx context.Context, in *DelOrdersReq, opts ...grpc.CallOption) (*DelOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelOrdersResp)
	err := c.cc.Invoke(ctx, Product_DelOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) GetOrdersById(ctx context.Context, in *GetOrdersByIdReq, opts ...grpc.CallOption) (*GetOrdersByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersByIdResp)
	err := c.cc.Invoke(ctx, Product_GetOrdersById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) SearchOrders(ctx context.Context, in *SearchOrdersReq, opts ...grpc.CallOption) (*SearchOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchOrdersResp)
	err := c.cc.Invoke(ctx, Product_SearchOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) AddProducts(ctx context.Context, in *AddProductsReq, opts ...grpc.CallOption) (*AddProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductsResp)
	err := c.cc.Invoke(ctx, Product_AddProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) UpdateProducts(ctx context.Context, in *UpdateProductsReq, opts ...grpc.CallOption) (*UpdateProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductsResp)
	err := c.cc.Invoke(ctx, Product_UpdateProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) DelProducts(ctx context.Context, in *DelProductsReq, opts ...grpc.CallOption) (*DelProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelProductsResp)
	err := c.cc.Invoke(ctx, Product_DelProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) GetProductsById(ctx context.Context, in *GetProductsByIdReq, opts ...grpc.CallOption) (*GetProductsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsByIdResp)
	err := c.cc.Invoke(ctx, Product_GetProductsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResp)
	err := c.cc.Invoke(ctx, Product_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productClient) UpdatesStatus(ctx context.Context, in *UpdatesStatusReq, opts ...grpc.CallOption) (*UpdatesStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatesStatusResp)
	err := c.cc.Invoke(ctx, Product_UpdatesStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServer is the server API for Product service.
// All implementations must embed UnimplementedProductServer
// for forward compatibility
type ProductServer interface {
	// -----------------------orderItems-----------------------
	AddOrderItems(context.Context, *AddOrderItemsReq) (*AddOrderItemsResp, error)
	UpdateOrderItems(context.Context, *UpdateOrderItemsReq) (*UpdateOrderItemsResp, error)
	DelOrderItems(context.Context, *DelOrderItemsReq) (*DelOrderItemsResp, error)
	GetOrderItemsById(context.Context, *GetOrderItemsByIdReq) (*GetOrderItemsByIdResp, error)
	SearchOrderItems(context.Context, *SearchOrderItemsReq) (*SearchOrderItemsResp, error)
	// -----------------------orders-----------------------
	AddOrders(context.Context, *AddOrdersReq) (*AddOrdersResp, error)
	UpdateOrders(context.Context, *UpdateOrdersReq) (*UpdateOrdersResp, error)
	DelOrders(context.Context, *DelOrdersReq) (*DelOrdersResp, error)
	GetOrdersById(context.Context, *GetOrdersByIdReq) (*GetOrdersByIdResp, error)
	SearchOrders(context.Context, *SearchOrdersReq) (*SearchOrdersResp, error)
	// -----------------------products-----------------------
	AddProducts(context.Context, *AddProductsReq) (*AddProductsResp, error)
	UpdateProducts(context.Context, *UpdateProductsReq) (*UpdateProductsResp, error)
	DelProducts(context.Context, *DelProductsReq) (*DelProductsResp, error)
	GetProductsById(context.Context, *GetProductsByIdReq) (*GetProductsByIdResp, error)
	SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error)
	UpdatesStatus(context.Context, *UpdatesStatusReq) (*UpdatesStatusResp, error)
	mustEmbedUnimplementedProductServer()
}

// UnimplementedProductServer must be embedded to have forward compatible implementations.
type UnimplementedProductServer struct {
}

func (UnimplementedProductServer) AddOrderItems(context.Context, *AddOrderItemsReq) (*AddOrderItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrderItems not implemented")
}
func (UnimplementedProductServer) UpdateOrderItems(context.Context, *UpdateOrderItemsReq) (*UpdateOrderItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderItems not implemented")
}
func (UnimplementedProductServer) DelOrderItems(context.Context, *DelOrderItemsReq) (*DelOrderItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelOrderItems not implemented")
}
func (UnimplementedProductServer) GetOrderItemsById(context.Context, *GetOrderItemsByIdReq) (*GetOrderItemsByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderItemsById not implemented")
}
func (UnimplementedProductServer) SearchOrderItems(context.Context, *SearchOrderItemsReq) (*SearchOrderItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOrderItems not implemented")
}
func (UnimplementedProductServer) AddOrders(context.Context, *AddOrdersReq) (*AddOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrders not implemented")
}
func (UnimplementedProductServer) UpdateOrders(context.Context, *UpdateOrdersReq) (*UpdateOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrders not implemented")
}
func (UnimplementedProductServer) DelOrders(context.Context, *DelOrdersReq) (*DelOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelOrders not implemented")
}
func (UnimplementedProductServer) GetOrdersById(context.Context, *GetOrdersByIdReq) (*GetOrdersByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersById not implemented")
}
func (UnimplementedProductServer) SearchOrders(context.Context, *SearchOrdersReq) (*SearchOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedProductServer) AddProducts(context.Context, *AddProductsReq) (*AddProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProducts not implemented")
}
func (UnimplementedProductServer) UpdateProducts(context.Context, *UpdateProductsReq) (*UpdateProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProducts not implemented")
}
func (UnimplementedProductServer) DelProducts(context.Context, *DelProductsReq) (*DelProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelProducts not implemented")
}
func (UnimplementedProductServer) GetProductsById(context.Context, *GetProductsByIdReq) (*GetProductsByIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsById not implemented")
}
func (UnimplementedProductServer) SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedProductServer) UpdatesStatus(context.Context, *UpdatesStatusReq) (*UpdatesStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatesStatus not implemented")
}
func (UnimplementedProductServer) mustEmbedUnimplementedProductServer() {}

// UnsafeProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServer will
// result in compilation errors.
type UnsafeProductServer interface {
	mustEmbedUnimplementedProductServer()
}

func RegisterProductServer(s grpc.ServiceRegistrar, srv ProductServer) {
	s.RegisterService(&Product_ServiceDesc, srv)
}

func _Product_AddOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).AddOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_AddOrderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).AddOrderItems(ctx, req.(*AddOrderItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_UpdateOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).UpdateOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_UpdateOrderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).UpdateOrderItems(ctx, req.(*UpdateOrderItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DelOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrderItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DelOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_DelOrderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DelOrderItems(ctx, req.(*DelOrderItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_GetOrderItemsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderItemsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetOrderItemsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_GetOrderItemsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetOrderItemsById(ctx, req.(*GetOrderItemsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_SearchOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrderItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).SearchOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_SearchOrderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).SearchOrderItems(ctx, req.(*SearchOrderItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_AddOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).AddOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_AddOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).AddOrders(ctx, req.(*AddOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_UpdateOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).UpdateOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_UpdateOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).UpdateOrders(ctx, req.(*UpdateOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DelOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DelOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_DelOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DelOrders(ctx, req.(*DelOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_GetOrdersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetOrdersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_GetOrdersById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetOrdersById(ctx, req.(*GetOrdersByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_SearchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).SearchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_SearchOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).SearchOrders(ctx, req.(*SearchOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_AddProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).AddProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_AddProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).AddProducts(ctx, req.(*AddProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_UpdateProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).UpdateProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_UpdateProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).UpdateProducts(ctx, req.(*UpdateProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_DelProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).DelProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_DelProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).DelProducts(ctx, req.(*DelProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_GetProductsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).GetProductsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_GetProductsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).GetProductsById(ctx, req.(*GetProductsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).SearchProducts(ctx, req.(*SearchProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Product_UpdatesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatesStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServer).UpdatesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Product_UpdatesStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServer).UpdatesStatus(ctx, req.(*UpdatesStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Product_ServiceDesc is the grpc.ServiceDesc for Product service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Product_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.product",
	HandlerType: (*ProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrderItems",
			Handler:    _Product_AddOrderItems_Handler,
		},
		{
			MethodName: "UpdateOrderItems",
			Handler:    _Product_UpdateOrderItems_Handler,
		},
		{
			MethodName: "DelOrderItems",
			Handler:    _Product_DelOrderItems_Handler,
		},
		{
			MethodName: "GetOrderItemsById",
			Handler:    _Product_GetOrderItemsById_Handler,
		},
		{
			MethodName: "SearchOrderItems",
			Handler:    _Product_SearchOrderItems_Handler,
		},
		{
			MethodName: "AddOrders",
			Handler:    _Product_AddOrders_Handler,
		},
		{
			MethodName: "UpdateOrders",
			Handler:    _Product_UpdateOrders_Handler,
		},
		{
			MethodName: "DelOrders",
			Handler:    _Product_DelOrders_Handler,
		},
		{
			MethodName: "GetOrdersById",
			Handler:    _Product_GetOrdersById_Handler,
		},
		{
			MethodName: "SearchOrders",
			Handler:    _Product_SearchOrders_Handler,
		},
		{
			MethodName: "AddProducts",
			Handler:    _Product_AddProducts_Handler,
		},
		{
			MethodName: "UpdateProducts",
			Handler:    _Product_UpdateProducts_Handler,
		},
		{
			MethodName: "DelProducts",
			Handler:    _Product_DelProducts_Handler,
		},
		{
			MethodName: "GetProductsById",
			Handler:    _Product_GetProductsById_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _Product_SearchProducts_Handler,
		},
		{
			MethodName: "UpdatesStatus",
			Handler:    _Product_UpdatesStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seckill.proto",
}
